version: '3'

services:

  db:
    image: 'mysql:5.7'
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: polaris
      MYSQL_DATABASE: polaris
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
